# Generated by Django 5.2.1 on 2025-07-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Product',
            name='ean',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
