# Generated by Django 5.2.1 on 2025-07-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_is_active_product_brand_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='manufacturercode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='productspecifications',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='realdimension',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_dimensions', to='Products.product'),
        ),
    ]
