# Generated by Django 5.2.1 on 2025-07-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_brand_category_remove_product_brand_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='Products.category'),
        ),
    ]
